backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "event"
    label: "Event"
    folder: "src/pages/event"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Datum Anlass", name: "date", widget: "date"}
      - {label: "Gültig von", name: "gueltigVon", widget: "datetime"}
      - {label: "Gültig bis", name: "gueltigBis", widget: "datetime"}
      - {label: "Bild Gross", name: "bildgross", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - name: "authors"
        label: "Authors"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}

  - name: "kitchenSink" # all the things in one entry, for documentation and quick testing
    label: "Kitchen Sink"
    folder: "_sink"
    create: true
    fields:
      - label: "Related Post"
        name: "post"
        widget: "relationKitchenSinkPost"
        collection: "posts"
        displayFields: ["title", "date"]
        searchFields: ["title", "body"]
        valueField: "title"
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Boolean", name: "boolean", widget: "boolean", default: true}
      - {label: "Text", name: "text", widget: "text"}
      - {label: "Number", name: "number", widget: "number"}
      - {label: "Markdown", name: "markdown", widget: "markdown"}
      - {label: "Datetime", name: "datetime", widget: "datetime"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "File", name: "file", widget: "file"}
      - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
      - {label: "Hidden", name: "hidden", widget: "hidden", default: "hidden"}
      - label: "Object"
        name: "object"
        widget: "object"
        fields:
          - label: "Related Post"
            name: "post"
            widget: "relationKitchenSinkPost"
            collection: "posts"
            searchFields: ["title", "body"]
            valueField: "title"
          - {label: "String", name: "string", widget: "string"}
          - {label: "Boolean", name: "boolean", widget: "boolean", default: false}
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Number", name: "number", widget: "number"}
          - {label: "Markdown", name: "markdown", widget: "markdown"}
          - {label: "Datetime", name: "datetime", widget: "datetime"}
          - {label: "Date", name: "date", widget: "date"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "File", name: "file", widget: "file"}
          - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
      - label: "List"
        name: "list"
        widget: "list"
        fields:
          - {label: "String", name: "string", widget: "string"}
          - {label: "Boolean", name: "boolean", widget: "boolean"}
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Number", name: "number", widget: "number"}
          - {label: "Markdown", name: "markdown", widget: "markdown"}
          - {label: "Datetime", name: "datetime", widget: "datetime"}
          - {label: "Date", name: "date", widget: "date"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "File", name: "file", widget: "file"}
          - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
          - label: "Object"
            name: "object"
            widget: "object"
            fields:
              - {label: "String", name: "string", widget: "string"}
              - {label: "Boolean", name: "boolean", widget: "boolean"}
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Number", name: "number", widget: "number"}
              - {label: "Markdown", name: "markdown", widget: "markdown"}
              - {label: "Datetime", name: "datetime", widget: "datetime"}
              - {label: "Date", name: "date", widget: "date"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "File", name: "file", widget: "file"}
              - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
              - label: "List"
                name: "list"
                widget: "list"
                fields:
                  - label: "Related Post"
                    name: "post"
                    widget: "relationKitchenSinkPost"
                    collection: "posts"
                    searchFields: ["title", "body"]
                    valueField: "title"
                  - {label: "String", name: "string", widget: "string"}
                  - {label: "Boolean", name: "boolean", widget: "boolean"}
                  - {label: "Text", name: "text", widget: "text"}
                  - {label: "Number", name: "number", widget: "number"}
                  - {label: "Markdown", name: "markdown", widget: "markdown"}
                  - {label: "Datetime", name: "datetime", widget: "datetime"}
                  - {label: "Date", name: "date", widget: "date"}
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "File", name: "file", widget: "file"}
                  - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
                  - {label: "Hidden", name: "hidden", widget: "hidden", default: "hidden"}
                  - label: "Object"
                    name: "object"
                    widget: "object"
                    fields:
                      - {label: "String", name: "string", widget: "string"}
                      - {label: "Boolean", name: "boolean", widget: "boolean"}
                      - {label: "Text", name: "text", widget: "text"}
                      - {label: "Number", name: "number", widget: "number"}
                      - {label: "Markdown", name: "markdown", widget: "markdown"}
                      - {label: "Datetime", name: "datetime", widget: "datetime"}
                      - {label: "Date", name: "date", widget: "date"}
                      - {label: "Image", name: "image", widget: "image"}
                      - {label: "File", name: "file", widget: "file"}
                      - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
